### ISSUE TITLE
Gridsome PWA Plugin Setup Issue

### ISSUE THREAD

**Issue by Matthew-Kanderka** [sethzindler/gridsome-boilerplate#1]
Hi,

I am working on my own Gridsome web app and I am using the gridsome pwa plugin but I am having some issues. I am wondering if you have encountered them?

When the service worker is setting up it returns this error in the console:

![image](https://user-images.githubusercontent.com/38925860/62752560-30fdb380-ba25-11e9-9fd4-451765643781.png)

It looks like the `assets/manifest/client.json` line in the generated service worker is causing the issue. I manually removed it from the dist folder and it setup the service worker fine.

Link to website: https://www.hummingbirdairsoft.com/
Link to Repo: https://github.com/Matthew-Kanderka/hummingbird-Airsoft-Web/tree/develop

Would you know a solution to this? Thanks

**Comment by sethzindler** [comment]
Looking at your live website, it looks like your service worker is registered and doing fine.

**Comment by sethzindler** [comment]
Also, you made an issue on this repository, which you are not using. If you have an issue with the PWA module, you need to leave it as an issue on the PWA author's page, not mine.

**Comment by Matthew-Kanderka** [comment]
Yes I understand that but when I deploy your code on AWS it gives the same error, so I was wondering if you have seen it before.

**Comment by sethzindler** [comment]
Sorry, I misunderstood you.

I took a look at the error (which now shows up on your website when I look), and it looks like a problem with your service worker code itself. Try using another type of service worker, i.e. offline page, offline copy of pages, cache-first network, etc. Try this site: https://www.pwabuilder.com/.

**Comment by Matthew-Kanderka** [comment]
Ok thanks, I'll try that out, when you manually wrote the service-wroker did it overwrite the one that is generated by the plugin?

**Comment by sethzindler** [comment]
To my knowledge, it will not overwrite the default service worker generated by the plugin. If you look at the plugin repository, you will see the default service worker the plugin generates. See here: https://github.com/rishabh3112/gridsome-plugin-pwa/blob/master/src/files/service-worker.js
